apiVersion: v1
kind: Service
metadata:
  name: {{ include "ks-devops.apiserver-fullname" . }}
  labels:
    {{- include "ks-devops-apiserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "ks-devops-apiserver.selectorLabels" . | nindent 4 }}
